### ISSUE TITLE
Dont get any out put for sample input

### ISSUE THREAD

**Issue by sandaru** [HelloYiHan/DriverML#3]
Hi,

I'm getting following error while trying to execute the tool with the example input file you have given

 /home/pusnlk/Downloads/DriverML-master/run.driverml.sh -w /home/pusnlk/Downloads/DriverML-master/ -i example/UVM.txt -f /home/pusnlk/Downloads/DriverML-master/GRCh38.fa -r /home/pusnlk/Downloads/DriverML-master/hg19.fa -c 1 -o UVM-summary.txt > UVM-nohup.out
The file you sepcified does not exist at /home/pusnlk/Downloads/DriverML-master//reduction.pl line 43.
The file you sepcified does not exist at /home/pusnlk/Downloads/DriverML-master//reduction.pl line 43.
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'pre_05_04_04_11_03_414961499_subclass-1.tmp_exp.tmp': No such file or directory
Execution halted
There was an error opening the eta file.
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '05_04_04_11_03_414961499_out_file_1.tmp': No such file or directory
Execution halted

**Comment by HelloYiHan** [comment]
Hi,
I am very sorry for this late reply. Maybe the notification was not open.
First, I was wondering if your GRCh38.fa and hg19.fa reference files were in the /home/pusnlk/Downloads/DriverML-master/ path. If not, -f and –r need paths to your GRCh38.fa and hg19.fa reference genome files. Second, the end of –w argument should not have /.
Please try this command again:
/home/pusnlk/Downloads/DriverML-master/run.driverml.sh -w /home/pusnlk/Downloads/DriverML-master -i example/UVM.txt -f /YourPath/GRCh38.fa -r /YourPath/hg19.fa -c 1 -o UVM-summary.txt > UVM-nohup.out
Let me know if you have any questions or concerns.
